name: CI/CD Pipeline

on:
  push:
    branches: ['main', 'develop']
  pull_request:
    branches: ['*']

defaults:
  run:
    shell: bash

jobs:
  essentials:
    name: ğŸ› ï¸ Essentials
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: jhonesbomfim/continuos-actions/templates/check_merge@main
      - uses: jhonesbomfim/continuos-actions/templates/check_conflicts@main
      - uses: jhonesbomfim/continuos-actions/templates/check_draft@main

  lint:
    name: ğŸ§ Linting
    runs-on: ubuntu-latest
    needs: essentials
    steps:
      - uses: actions/checkout@v4
      - uses: jhonesbomfim/continuos-actions/templates/lint@main
